---
apiVersion: v2
kind: DefaultJob
id: MergeRequestLLMReviewer_123456_optimize
name: 自动化AI代码审核
description: 使用大模型来对codeup的merge request进行review，并自动提交评论
helpUrl: https://help.aliyun.com/zh/yunxiao/user-guide/use-flow-cli-to-customize-development-steps
execution:
  executor: node
  main: dist/index.js
items:
  - label: 模型名称
    name: modelName
    type: dropdown
    datasource:
    - label: deepseek-r1
      value: deepseek-r1
    - label: deepseek-v3
      value: deepseek-v3
    - label: qwen-max
      value: qwen-max
    - label: qwen-turbo-latest
      value: qwen-turbo-latest
    - label: qwen-turbo
      value: qwen-turbo
    - label: qwen-plus
      value: qwen-plus
    value: deepseek-v3
  - label: 云效token
    name: yunxiaoToken
    type: input
    description: 可以引用私密配置项 ${YUNXIAO_TOKEN},需要在流水线编辑页的变量与缓存中配置该变量的具体值
  - label: 百炼APIKey
    name: dashscopeApikey
    type: input
    description: 可以引用私密配置项 ${BAILIAN_APIKEY},需要在流水线编辑页的变量与缓存中配置该变量的具体值
  - label: 模型温度值
    name: temperature
    type: input
    description: 调用大模型时的温度值，默认为0.2
    value: "0.2"
  - label: 大模型提示词
    name: llmChatPrompt
    type: input
    description: 调用大模型时的系统角色
    value: "你是一位资深 Java 开发工程师和代码评审专家，专注于Web应用的安全性、稳定性与性能。
       你的任务是对提交的代码变更进行严格审查    
          仅指出以下类型的严重问题： 
            1. 逻辑错误：可能导致业务流程异常、数据不一致、死循环、方法内执行逻辑不自洽的空指针、逻辑缺陷、边界条件未处理、循环控制不严谨、状态管理混乱等运行时崩溃。 
            2. 安全隐患：如 SQL 注入、数据权限绕过、敏感信息泄露等。 
            3. 资源泄漏：如数据库连接未关闭、文件流未释放、线程池未正确关闭等
            4. 并发问题：是否有较大可能引发并发问题、资源泄漏、性能瓶颈等运行时问题。 
            5. SQL性能优化：仅限数据库操作代码，如慢查询、全表扫描、缺少索引、N+1 查询、大结果集处理不当、无分页返回大量数据、无限递归导致栈溢出等。 
            6. 对于空指针：只有代码执行逻辑不自洽的空指针才需你评审
            7. 关注内容：对于删除内容无需检测只关注新增/修改内容的代码
          输出规则： 
            - 仅列出严重影响系统运行、安全或性能的问题
            - 不输出无关紧要的内容（如命名规范、空行、日志打印、格式美化）
            - 仅使用中文列出具体问题，无需解释原因 
            - 若无问题，请直接回复：\"没问题\"
            - 禁止使用任何 Markdown 格式
            - 不添加任何前缀或后缀内容，如“问题如下：”、“建议：”等 
            - 如果有多个问题，每个问题单独成行，按编号顺序列出即可"

