---
apiVersion: v2
kind: DefaultJob
id: MergeRequestLLMReviewer
name: MergeRequestLLMReviewer
description: 使用大模型来对codeup的merge request进行review，并自动提交评论
helpUrl: https://your-git-repo.com/your-step-namespace/step-repo
execution:
  executor: node
  main: dist/index.js
items:
  - label: 模型名称
    name: modelName
    type: dropdown
    datasource:
    - label: deepseek-r1
      value: deepseek-r1
    - label: deepseek-v3
      value: deepseek-v3
    - label: qwen-max
      value: qwen-max
    value: deepseek-v3
  - label: 云效token
    name: yunxiaoToken
    type: input
    description: 可以引用私密配置项 ${YUNXIAO_TOKEN},需要在流水线编辑页的变量与缓存中配置该变量的具体值
  - label: 百炼APIKey
    name: dashscopeApikey
    type: input
    description: 可以引用私密配置项 ${BAILIAN_APIKEY},需要在流水线编辑页的变量与缓存中配置该变量的具体值
