---
apiVersion: v2
kind: DefaultJob
id: MergeRequestLLMReviewer_665ec846262ae18c316677c2_optimize
name: 自动化AI代码审核
description: 使用大模型来对codeup的merge request进行review，并自动提交评论
helpUrl: https://help.aliyun.com/zh/yunxiao/user-guide/use-flow-cli-to-customize-development-steps
execution:
  executor: node
  main: dist/index.js
items:
  - label: 模型名称
    name: modelName
    type: dropdown
    datasource:
    - label: deepseek-r1
      value: deepseek-r1
    - label: deepseek-v3
      value: deepseek-v3
    - label: qwen-max
      value: qwen-max
    - label: qwen-turbo-latest
      value: qwen-turbo-latest
    - label: qwen-turbo
      value: qwen-turbo
    - label: qwen-plus
      value: qwen-plus
    value: deepseek-v3
  - label: 云效token
    name: yunxiaoToken
    type: input
    description: 可以引用私密配置项 ${YUNXIAO_TOKEN},需要在流水线编辑页的变量与缓存中配置该变量的具体值
  - label: 百炼APIKey
    name: dashscopeApikey
    type: input
    description: 可以引用私密配置项 ${BAILIAN_APIKEY},需要在流水线编辑页的变量与缓存中配置该变量的具体值
  - label: 大模型提示词
    name: llmChatPrompt
    type: input
    description: 调用大模型时的系统角色
    value: "请扮演资深代码评审专家,结合审查要求进行代码审查任务 你的任务是对提交的代码变更进行严格审查
                                聚焦以下维度： 
                                  1. 冗余代码：是否存在无用的条件判断、重复方法调用、死代码、可简化逻辑等。 
                                  2. 逻辑错误：是否有明显逻辑缺陷、边界条件未处理、循环控制不严谨、状态管理混乱等问题。 
                                  3. 潜在问题：是否有较大可能引发并发问题、资源泄漏、性能瓶颈等运行时问题。 
                                  4. SQL性能优化：检查数据库操作相关代码，包括但不限于查询语句效率低下、索引未使用、不必要的全表扫描、大事务等。 
                                  5. 以上内容仅在不影响性能、严重可读性、严重缺陷的情况下其他如注释 代码风格的可忽略仅聚焦严重问题，对于空指针检查范围仅限在方法内执行逻辑不自洽的空指针，其他如参数未判断null可忽略
                                输出规则： 
                                  - 仅使用中文列出具体问题，无需解释原因 
                                  - 若无问题，请直接回复：\"没问题\"
             - 禁止使用任何 Markdown 格式
             - 不添加任何前缀或后缀内容，如“问题如下：”、“建议：”等 - 每个问题单独成行，编号由系统自动生成，你只需按顺序列出即可
             - 如果有多个问题，请分行列出，每行一个问题额外指导： "

